trigger:
- main

variables:
- name: yaml_folder
  value: $(System.DefaultWorkingDirectory)/k8s-yaml-sample
- name: chart_folder
  value: $(System.DefaultWorkingDirectory)/helm-chart-sample

pool:
  vmImage: ubuntu-latest

steps:

- script: |
      docker run -v /k8s-yaml-sample:/yaml stackrox/kube-linter lint /yaml
  displayName: Run Static KubeLinter Code analysis for Kubernetes YAML manifest files
  continueOnError: true
  
- script: |
      docker run -v /helm-chart-sample:/chart stackrox/kube-linter lint /chart
  displayName: Run KubeLinter Static Code analysis for Helm Chart
  continueOnError: true
